#ifndef _SFG_SETTINGS_H
#define _SFG_SETTINGS_H

#define SFG_FPS 60
#define SFG_RESOLUTION_X 1024
#define SFG_RESOLUTION_Y 768

#define SFG_DITHERED_SHADOW 1

#define SFG_RAYCASTING_MAX_STEPS 30

#define SFG_RAYCASTING_MAX_HITS 10

#endif // guard
